[templates.waybar]
input_path = '~/.config/waybar/style.css.template'
output_path = '~/.config/waybar/style.css'
pre_hook = 'pkill waybar'
post_hook = 'waybar > /dev/null & disown'

[templates.sway]
input_path = '~/.config/sway/config.template'
output_path = '~/.config/sway/config'

[templates.niri]
input_path = '~/.config/niri/config.kdl.template'
output_path = '~/.config/niri/config.kdl'

[templates.mako]
input_path = '~/.config/mako/config.template'
output_path = '~/.config/mako/config'
post_hook = 'makoctl reload'

[templates.vicinae]
input_path = '~/.config/vicinae/themes/matugen.toml.template'
output_path = '~/.local/share/vicinae/themes/matugen.toml'
post_hook = 'vicinae server > /dev/null & disown'

[templates.vesktop]
input_path = '~/.config/vesktop/themes/midnight-discord.css.template'
output_path = '~/.config/vesktop/themes/midnight-discord.css'

[templates.gtklock_css]
input_path = '~/.config/gtklock/style.css.template'
output_path = '~/.config/gtklock/style.css'

[templates.screenshot_sh]
input_path = '~/scripts/screenshot.sh.template'
output_path = '~/scripts/screenshot.sh'

[templates.record_sh]
input_path = '~/scripts/record.sh.template'
output_path = '~/scripts/record.sh'

[templates.clock_settings]
input_path = '~/.config/gtklock/clock-settings.template'
output_path = '~/.config/gtklock/clock-settings'

[templates.rofi]
input_path = '~/.config/rofi/config.rasi.template'
output_path = '~/.config/rofi/config.rasi'

[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "center"]
set = true
